### ISSUE TITLE
close() database function should be async

### ISSUE THREAD

**Issue by matjazv** [LiskHQ/lisk-db#74]
### Expected behavior

When running unit tests in [report_misbehavior_transaction.spec.ts ](https://github.com/LiskHQ/lisk-sdk/blob/development/framework/test/integration/node/processor/report_misbehavior_transaction.spec.ts) in `lisk-sdk`, there should be no `Jest` warnings regarding open handle for database connection.

### Actual behavior

After running unit tests, `Jest` reports a warning regarding open handles for database connection:

```
Jest has detected the following 1 open handle potentially keeping Jest from exiting:

  ●  neon threadsafe function

      159 |
      160 |     removeDB(systemDir.data);
    > 161 |     const moduleDB = new Database(path.join(systemDir.data, 'module.db'));
          |                      ^
      162 |     const stateDB = new StateDB(path.join(systemDir.data, 'state.db'));
      163 |
      164 |     const validatorsModule = new ValidatorsModule();

      at new Database (../node_modules/@liskhq/lisk-db/database.js:85:20)
      at Object.getBlockProcessingEnv (src/testing/block_processing_env.ts:161:19)
      at Object.<anonymous> (test/integration/node/processor/report_misbehavior_transaction.spec.ts:35:30)
```

### Steps to reproduce

In `lisk-sdk/framework` directory execute:
`$ yarn test:integration report --detectOpenHandles`

### Which version(s) does this affect? (Environment, OS, etc...)

Current [main](https://github.com/LiskHQ/lisk-db/tree/main) branch.

**Comment by matjazv** [comment]
`Jest` reports a warning regarding open handles for database connection because Node.js `Garbage Collector` is not exposed during unit test execution.

We may see in [neon-bindings library](https://github.com/neon-bindings/neon/) in [unit tests for thread](https://github.com/neon-bindings/neon/blob/main/test/napi/lib/threads.js#L5) a warning regarding GC:

> // These tests require GC exposed to shutdown properly; skip if it is not

After [each unit test](https://github.com/neon-bindings/neon/blob/main/test/napi/lib/threads.js#L21) GC is forced to be executed:

> // Force garbage collection to shutdown `Channel`

A code under our unit test for which `Jest` reports a warning regarding open handles for database connection is using exactly the same primitives (`threads` and `channels`) so it is exposed to the same issues regarding GC as stated above.

Options which were considered during resolving this issue and did not bring any success:
- not using `std::thread` and synchronously send data to a channel
- wait for a thread to complete before continuing with remaining code execution
- make `close()` function `async` and `awaited` for it
- manually drop `Database` object in `Finalize` trait
